- hosts: all
  tasks:
    - name: Uptime of servers
      register: uptimeofserv
      command: "uptime"

    - debug:
        var: uptimeofserv.stdout_lines

    - name: Execute the df command
      register: dfout
      command: "df -h"

    - debug:
        var: dfout.stdout_lines
