---
- hosts: all
  vars:
    ansible_user: 'root'
    ansible_password: 'vagrant'

  tasks:
    - name: Create a directory
      ansible.builtin.file:
        path: /var/tmp/newdir1
        state: directory
