- hosts: all
  tasks:
    - name: Check uptime
      shell: uptime
      register: uptime_result

    - name: Get current working directory
      command: pwd
      register: pwd_result

    - name: Display uptime result
      debug:
        var: uptime_result

    - name: Display current working directory
      debug:
        var: pwd_result.stdout

    - name: Clone a public GitHub repository into the current working directory
      ansible.builtin.git:
        repo: 'https://github.com/Ivista/testrepo.git'
        dest: "{{ pwd_result.stdout }}/testrepo"
        version: 'main'

    - name: List files and folders in the cloned repository
      command: ls -la "{{ pwd_result.stdout }}/testrepo"
      register: repo_contents

    - name: Display contents of the repository
      debug:
        var: repo_contents.stdout

    - name: List contents of a directory
      hosts: localhost
      tasks:
        - name: Run the 'ls' command
          command: ls -la /home/vagrant
          register: dir_output
    
        - name: Print directory contents
          debug:
            var: dir_output.stdout_lines
