- hosts: all
  tasks:
    - name: Check uptime
      shell: uptime
      register: uptime_result

    - name: Get current working directory
      command: pwd
      register: pwd_result

    - name: Display uptime result
      debug:
        var: uptime_result

    - name: Display current working directory
      debug:
        var: pwd_result.stdout

    - name: Clone a public GitHub repository into the current working directory
      ansible.builtin.git:
        repo: 'https://github.com/Ivista/testrepo.git'
        dest: "{{ pwd_result.stdout }}/testrepo"
        version: 'main'

    - name: List files and folders in the cloned repository
      command: ls -la "{{ pwd_result.stdout }}/testrepo"
      register: repo_contents

    - name: Display contents of the repository
      debug:
        var: repo_contents.stdout

# A new play for listing the contents of a directory on localhost
- hosts: vagrant ansible tower serv
  remote_user: vagrant
  become: yes
  become_user: root
  become_method: su
  vars:
    ansible_become_pass: vagrant  # Root password is set here (Not recommended for security reasons)
  tasks:
    - name: List the contents of /root directory as root
      command: ls -la /root
      register: dir_contents

    - name: Display the contents of the /root directory
      debug:
        var: dir_contents.stdout_lines

