---
- hosts: all
  vars:
    ansible_user: 'username'
    ansible_password: 'password'

  tasks:
    - name: Create a directory
      ansible.builtin.file:
        path: /path/to/directory
        state: directory
