- hosts: 192.168.56.15  # Use your inventory name in Ansible Tower
  remote_user: root  # Connect directly as root
  vars:
    ansible_password: vagrant  # Set the root password directly here if needed
  tasks:
    - name: Check uptime as root
      command: uptime
      register: uptime_result

    - name: Display the uptime result
      debug:
        var: uptime_result.stdout

    - name: List the contents of /root directory as root
      command: ls -la /root  # Lists the contents of /root directory
      register: dir_contents

    - name: Display the contents of the /root directory
      debug:
        var: dir_contents.stdout_lines
