- hosts: 192.168.56.15  # Use your inventory name in Ansible Tower
  remote_user: root  # Connect directly as root
  vars:
    ansible_password: vagrant  # Set the root password directly here if needed
    project_folder: /home/vagrant/work/anstowertest
  tasks:
    - name: Check uptime as root
      command: uptime
      register: uptime_result

    - name: Display the uptime result
      debug:
        var: uptime_result.stdout

    - name: List the contents of /root directory as root
      command: ls -la /root  # Lists the contents of /root directory
      register: dir_contents

    - name: Display the contents of the /root directory
      debug:
        var: dir_contents.stdout_lines

    - name: clean up 
      shell: /bin/rm -rf "{{project_folder}}"/extracted_data/*
      register: cleanup_result
      
    - debug:
        var: cleanup_result.stdout_lines

    - name: upate local repo git pull only
      command:
        chdir: "{{project_folder}}"
        cmd: git pull
      register: gitpullrepo

    - debug:
        var: gitpullrepo.stdout_lines

